print("HHHHH      HHHHH     EEEEEEEEEEEEEEE     LLLLL               LLLLL                    OOOOO")
print("HHHHH      HHHHH     EEEEEEEEEEEEEE      LLLLL               LLLLL                 OOOOOOOOOOO")
print("HHHHH      HHHHH     EEEEE               LLLLL               LLLLL               OOOOO     OOOOO")
print("HHHHHHHHHHHHHHHH     EEEEEEEEEEEEEE      LLLLL               LLLLL               OOOO       OOOO")
print("HHHHHHHHHHHHHHHH     EEEEEEEEEEEEEE      LLLLL               LLLLL               OOOO       OOOO")
print("HHHHH      HHHHH     EEEEE               LLLLL               LLLLL               OOOOO     OOOOO")
print("HHHHH      HHHHH     EEEEEEEEEEEEEE      LLLLLLLLLLLLLLL     LLLLLLLLLLLLLLL       OOOOOOOOOOO")
print("HHHHH      HHHHH     EEEEEEEEEEEEEEE     LLLLLLLLLLLLLLL     LLLLLLLLLLLLLLL          OOOOO")
print("")
print("WW            WW          OOOOO          RRRRRRRRR           LLLLL               DDDDDDDDDD")
print("WWW          WWW       OOOOOOOOOOO       RRR    RRR          LLLLL               DDDDDDDDDDDDD")
print("WWWW   WW   WWWW     OOOOO     OOOOO     RRR    RRRR         LLLLL               DDDD     DDDDDD")
print("WWWWW WWWW WWWWW     OOOOO     OOOOO     RRR    RRR          LLLLL               DDDD       DDDD")
print(" WWWWWWWWWWWWWW      OOOOO     OOOOO     RRRRRRRRR           LLLLL               DDDD       DDDD")
print("  WWWWWWWWWWWW       OOOOO     OOOOO     RRRR    RRR         LLLLL               DDDD     DDDDDD")
print("   WWWWWWWWWW          OOOOOOOOOOO       RRRR     RRR        LLLLLLLLLLLLLLL     DDDDDDDDDDDDD")
print("    WW    WW              OOOOO          RRRR      RRRR      LLLLLLLLLLLLLLL     DDDDDDDDDD")
